baseurl: "https://javaswag.github.io"
title: "Javaswag"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
paginate: 50
uglyURLs: false
metaDataFormat: "yaml"
LanguageCode: ru
params:
  itunes: https://podcasts.apple.com/podcast/id1498075914
  android: https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5mZWVkYnVybmVyLmNvbS9tb3ZpZXRhbGtzL3BvZGNhc3Q?sa=X&ved=0CAIQ9sEGahgKEwjYh-vYkef2AhUAAAAAHQAAAAAQ2wY
  feed: /index.xml
  desc: Подкаст о разработке на Java. Все то, о чем вы боялись спросить в кулуарах.
  summary: Подкаст о разработке на Java
  StaticURL: "https://javaswag.github.io"
  LanguageCode: ru
  yandexS3: "https://storage.yandexcloud.net/javaswag/"
  telegram: https://t.me/javaswag
permalinks:
  post: "/:title"
